version: '3'
services:
  traceip:
    image: "traceip"
    environment:
      - REDIS_HOST=redis
      
    ports:
      - "8000:8001"
      
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    